version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      TELEGRAM_BOT_TOKEN: ${APP_TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_SECRET_TOKEN: ${APP_TELEGRAM_BOT_SECRET_TOKEN}
      TELEGRAM_BOT_WHITELISTED_USERS_ID: ${APP_TELEGRAM_BOT_WHITELISTED_USERS_ID}
      OPEN_AI_API_KEY: ${APP_OPEN_AI_API_KEY}
      OPEN_AI_GPT_MODEL: ${APP_OPEN_AI_GPT_MODEL}
      OPEN_AI_GPT_SYSTEM_MESSAGE: ${APP_OPEN_AI_GPT_SYSTEM_MESSAGE}
      OPEN_AI_GPT_CONTEXT_MESSAGES_QTY: ${APP_OPEN_AI_GPT_CONTEXT_MESSAGES_QTY}
      OPEN_AI_GPT_CONTEXT_LIMIT_IN_TOKENS: ${APP_OPEN_AI_GPT_CONTEXT_LIMIT_IN_TOKENS}
      OPEN_AI_GPT_RESPONSE_LIMIT_IN_TOKENS: ${APP_OPEN_AI_GPT_RESPONSE_LIMIT_IN_TOKENS}
    ports:
      - '8080:8080'